### ISSUE TITLE
HTML Build Error

### ISSUE THREAD

**Issue by mballschmiede** [w201rdada/portfolio-mballschmiede#7]
Hi Brooks, 

I'm getting the following error when I try to "run script" in the top right corner of the _build.sh tab. Any idea what I'm doing wrong? 

> system("./_build.sh")
./_build.sh: line 3: cd: /home/oski/: No such file or directory
27 Nov 2017 03:00:00 [rsession-] WARNING PrivateCommand timeout; LOGGED FROM: bool rstudio::core::terminal::PrivateCommand::onTryCapture(rstudio::core::system::ProcessOperations&, bool) /home/ubuntu/rstudio/src/cpp/core/terminal/PrivateCommand.cpp:102
> traceback()
No traceback available 

Thanks in advance!
Michael

**Comment by jab684** [comment]
Try changing "oski" to "rstudio"! That worked for me.

**Comment by mballschmiede** [comment]
Boom. That worked. Thanks for the help (and quick response) Julia!
